---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    author: anil
    type: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_DB
          value: mydb
...