---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    author: anil
    type: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    author: anil
    type: postgres
...