---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    author: anil
    type: redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    author: anil
    type: redis
...