---
apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    author: anil
    type: result-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    author: anil
    type: result-app
...