---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    author: anil
    type: app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30002
  selector:
    author: anil
    type: voting-app
...
