---
apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  labels:
    author: anil
    type: voting-app
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
...
