---
apiVersion: v1
kind: Pod
metadata:
  name: worker-app
  labels:
    author: anil
    type: worker-app
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
...